apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- application
- pipeline
- mysql
resources:
- pipeline-application.yaml
images:
- name: myonlyzzy/api-server
  newTag: 1.0.0-rc.1
- name: myonlyzzy/persistenceagent
  newTag: 1.0.0-rc.1
- name: myonlyzzy/scheduledworkflow
  newTag: 1.0.0-rc.1
- name: myonlyzzy/frontend
  newTag: 1.0.0-rc.1
- name: myonlyzzy/viewer-crd-controller
  newTag: 1.0.0-rc.1
- name: myonlyzzy/visualization-server
  newTag: 1.0.0-rc.1
- name: myonlyzzy/metadata-writer
  newTag: 1.0.0-rc.1
- name: myonlyzzy/cache-server
  newTag: 1.0.0-rc.1
- name: myonlyzzy/cache-deployer
  newTag: 1.0.0-rc.1
# Used by Kustomize
configMapGenerator:
- name: pipeline-install-config
  env: params.env
secretGenerator:
- name: mysql-secret
  env: params-db-secret.env
vars:
- name: NAMESPACE
  objref:
    kind: Deployment
    apiVersion: apps/v1
    name: ml-pipeline
  fieldref:
    fieldpath: metadata.namespace
- name: APP_NAME
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appName
- name: APP_VERSION
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appVersion
- name: DBSERVICE_HOST
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.dbHost
- name: DBSERVICE_PORT
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.dbPort
- name: DBNAME_MLMD
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.mlmdDb
- name: DBNAME_CACHE
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.cacheDb
- name: DBNAME_PIPELINE
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.pipelineDb
- name: BUCKET_NAME
  objref:
    kind: ConfigMap
    name: pipeline-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.bucketName
configurations:
- params.yaml
